### ISSUE TITLE
includeJsModule being quirky

### ISSUE THREAD

**Issue by michaelroper** [nystudio107/craft-twigpack#13]
Hey Andrew,

Seeing some odd behaviour in the latest version (v1.1.5), where when using the includeJsModule function like this: 

`{{ craft.twigpack.includeJsModule("app.js", true) }}`

.. so, it doesn't seem to be getting the most recent file reference from the `manifest.json` for the modern JS bundle, but it _is_ getting the correct reference to the legacy JS bundle from the `manifest-legacy.json` file, and the CSS reference further up the page is also working correctly as well. (can provide test urls if needed)

Have tried clearing all the caches, deleting runtime folders, redeploying, restarting, etc etc..

**Comment by khalwat** [comment]
Twigpack uses whatever you've set for the data cache to cache file contents (including your manifest.json).

However, the same method is used to get things from either manifest, so if it works for one, but not the other... makes me think the problem might be elsewhere.

Not a while lot changed in the 1.1.5 update, so unless it was a latent bug that's been there all along (but was masked by the wrong key being used for the cache), not sure how the changes could affect this.

**Comment by michaelroper** [comment]
yeah, i had a look through the commit changes and couldn't see anything that stood out as possibly affect it... just a coincidence that it started playing up today after updating... 🤔

**Comment by khalwat** [comment]
I'll update on my production envs and let you know if I see anything.

Meantime, it's going to be either:

* It's storing the `manifest.json` in the data cache, and for whatever reason, it's not cleared
* It's not obtaining the `manifest.json` from where you think it is

I'm _reasonably_ certain this isn't due to a change on my end, but we'll see.

**Comment by michaelroper** [comment]
So, as mentioned, this was fixed with a server reboot. 😒
