### ISSUE TITLE
Easy way to test production bundle.

### ISSUE THREAD

**Issue by knynkwl** [nystudio107/craft-twigpack#19]
Right now I have to switch:

```
'server' => [
    'manifestPath' => 'http://localhost:8080/',
    'publicPath' => '/',
],
```

to

```
'server' => [
    'manifestPath' => '/_compiled/',
    'publicPath' => '/',
 ],
```

and set `useDevServer` to false

```
'local' => [
    'useDevServer' => false,
 ],
```

in order to view the compiled files. Is there an eaiser way to set this up? It would be great if we knew if the devserver was running.

**Comment by knynkwl** [comment]
While testing, it seems like when `useDevServer` is true, it doesn't seem to use the `devServer` config, and just reverts to `server` config instead.

**Comment by khalwat** [comment]
It only uses the `server` config if it can't connect to the `devServer`

To test the production bundle, you don't need to change the config -- just don't have the dev server running.

It sounds to me like something is not right with your setup. Check the default config that ships with it and compare it to what you're using. Note it is using a file path alias for the `manifestPath`
