### ISSUE TITLE
Missing css files when using dev-server

### ISSUE THREAD

**Issue by woutsluiter** [nystudio107/craft-twigpack#2]
Hi,

When I use webpack-dev-server I'm using the `style-loader` instead of the `MiniCssExtractPlugin.loader` so my styles are also Hot reloaded. But it also means it doesn't output a css file. In my base layout I have the following line:
```
{{ craft.twigpack.includeCssModule("index.css") }}
```
which normally points to an extracted css file from index.js, but in dev-server mode it's missing from the manifest. Any idea how to handle this?

**Comment by khalwat** [comment]
So it's fine, Twigpack considers a missing CSS module as a "soft" error in local dev, so your `style-loader` can do its injection thing, and you can leave that tag in there (it just outputs nothing if the `index.css` or whatever is not found).

**Comment by woutsluiter** [comment]
Sorry not sure what you mean with "soft" error. I'm getting a full thrown exception and have to work around with the devMode variable. But I don't think that's the solution here. Can this output be silenced? Or better yet, is there a way to expose in twig that dev-server is running?

**Comment by khalwat** [comment]
Update to the latest version of Twigpack @woutsluiter ? I'm using the same setup you are, and in a more recent version, I made it throw a soft error (it just logs it, but then returns an empty string).

This allows things to work without an issue for cases where you'd doing HMR with the CSS via `style-loader`

**Comment by woutsluiter** [comment]
Upgraded and solved 👍. Thanks for the quick response!
