### ISSUE TITLE
Question about Prefetch/Preload

### ISSUE THREAD

**Issue by devanflaherty** [nystudio107/craft-twigpack#21]
Hey Andrew,

I see that this plugin works in regards to prefetching/loading the entry points, but was curious how you handle prefetching/loading of dynamic imports(lazy components) js and css.

Vue Cli extracts all the CSS and by default will create prefetch/preload links, but haven't found the best practice for including these. For now we've turn the extraction of CSS off but was curious what a best practice is here and how Twig Pack could help us out.

**Comment by khalwat** [comment]
This is something I'd handle through JavaScript, such as preloading these things on _intent_ like a mouse over or such. Have a look here:

https://github.com/nystudio107/devmode/blob/master/src/js/app.js#L40
