### ISSUE TITLE
CSS file loaded asynchronously doesn’t work in Firefox

### ISSUE THREAD

**Issue by jesuismaxime** [nystudio107/craft-twigpack#22]
Nothing to add, if using `{{ craft.twigpack.includeCssModule("app.css", true) }}` the fallback doesn’t seem to work in Firefox (v69.0b16).

**Comment by khalwat** [comment]
Are you including the:

```twig
{{ craft.twigpack.includeCssRelPreloadPolyfill() }}
```
?

**Comment by jesuismaxime** [comment]
Nope? Seems thats more a must than a simple polyfill. Before or after the `includeCssModule` ?

Thanks

**Comment by khalwat** [comment]
Yes, before. And it should be a simple polyfill.
