### ISSUE TITLE
Multisite issues with manifest file

### ISSUE THREAD

**Issue by furioursus** [nystudio107/craft-twigpack#24]
If I have a multisite environment, such as `site.test` and `site.test/jp`, Twigpack creates the URL for the manifest file using the full `siteUrl`, such that what would normally be `http://site.test/assets/css/app.css?id=31b936e9b9364486cabb` is now `http://site.test/jp/assets/css/app.css?id=31b936e9b9364486cabb`. Is there a config override for this or some way to alias the language/site url to point to the original file?

**Comment by khalwat** [comment]
So the way to do this would be to set your `SITE_URL` environment variable to just the domain, and then use that in your Twigpack settings.

Then use that + the suffix in your `general.php` settings.
