### ISSUE TITLE
isHot not set properly before use

### ISSUE THREAD

**Issue by bighoho123** [nystudio107/craft-twigpack#30]
Hello,

In the `helpers\Manifest::getModule` function the static const $isHot is used but without properly set.

I've created a PR for that. If you could merge it when you've got a chance that would be great.

Thanks.

#29

**Comment by khalwat** [comment]
Fixed in 1.1.9 via your PR. Thanks!

**Comment by khalwat** [comment]
I'm actually going to revert this, because the logic for `self::$isHot` is set in the higher level functions. If this module "resets" it each time, then the fallback on the non-hot no longer works.
