### ISSUE TITLE
Have you considered this method for asynchronous loading css?

### ISSUE THREAD

**Issue by terryupton** [nystudio107/craft-twigpack#33]
A newer perhaps simpler approach to asynchronously loading css

https://www.filamentgroup.com/lab/load-css-simpler/

Is this something worth considering for twigpack?

**Comment by khalwat** [comment]
Yep, I've seen it -- probably I'll switch over to it at some point.

**Comment by khalwat** [comment]
That's what it uses now in 1.2.0!

https://github.com/nystudio107/craft-twigpack/releases/tag/1.2.0
