### ISSUE TITLE
`craft.twigpack.includeFileFromManifest` isn't inserting anything

### ISSUE THREAD

**Issue by rjgux** [nystudio107/craft-twigpack#34]
Our `manifest.json` and `webapp.html` files are being generated as expected, and a reference to the `webapp.html` file is in the manifest -

```
"webapp.html": "/assets/bundled/webapp.html"
```

All the paths and file contents look correct, but `{{ craft.twigpack.includeFileFromManifest("webapp.html") }}` isn't inserting any markup. This has been working correctly up until recently and we haven't changed anything in the build setup, so think it must be a recent update?

Craft version 3.3.11
Twigpack version 1.1.11

**Comment by khalwat** [comment]
Check your `web.log` for errors?

**Comment by francescomugnai** [comment]
Same problem here.
It worked perfectly, now (after a composer update) isn't inserting any markup anymore.
Web.log is clean.

Craft: 3.3.15
Twigpack: 1.1.11
Twig: 2.12.1

On the composer.json I've:
```
    "craftcms/cms": "^3.0.0",
    "craftcms/redactor": "2.3.3.2",
    "nystudio107/craft-twigpack": "^1.1",
    "twig/twig": "^2.12.1",
    "verbb/knock-knock": "^1.1",
    "vlucas/phpdotenv": "^2.4.0"
```

**Comment by khalwat** [comment]
I think I'm seeing this too.

**Comment by khalwat** [comment]
I think this is due to https://github.com/nystudio107/craft-twigpack/pull/26 -- investigating

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-twigpack/commit/6e27346dbbf86f4b3772c34707038aab157b5ebc
