### ISSUE TITLE
[FR] CSP nonce support

### ISSUE THREAD

**Issue by tomkiss** [nystudio107/craft-twigpack#40]
Hi there,

I recently purchased a license, all seems to be working great, thanks!

I'm configuring my Content-Security-Policy headers and am looking to enable `strict-dynamic`, which would require `nonce` attributes on my outputted script/style tags.

Is there any way I can achieve this?

ie:

Current input:
```
{{ craft.twigpack.includeCriticalCssTags() }}
{{ craft.twigpack.includeSafariNomoduleFix() }}
```

Current output:
```
<style>.styles{}</style>
<script>
!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
</script>
```

Desired output:

```
<style nonce="mynoncehash1">.styles{}</style>
<script nonce="mynoncehash2">
!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()},!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();
</script>
```

Maybe just a way to access the script or style tag contents directly would do, rather than the script/style tag html markup around it.

Thanks 🙏

*Edit: Apologies my previous example was complete garbage. Baby brain.

**Comment by khalwat** [comment]
@tomkiss I'm slightly confused, there is no license for Twigpack, it's free?

**Comment by khalwat** [comment]
So there's no `nonce` support currently, but I would be open to adding it if you like.

PRs are welcome too.

**Comment by khalwat** [comment]
@tomkiss Where would the value in `nonce=""` come from? Would it be a constant you pass in, or would it be from the webpack generated hash or...?

**Comment by tomkiss** [comment]
Hi, sorry for the delayed response.

The nonce itself is unique for each request, so wouldn't be part of the build process. I've less experience of nonces on PHP projects and more from React - but I notice that there is a Craft plugin that supports nonces for CSP out there, at least as one implementation example:
https://plugins.craftcms.com/content-security-policy

*RE: "buying a license", lol - I went on a bit of a license-buying rampage and lost track a bit. Aforementioned baby-brain something to do with the confusion perhaps :)

**Comment by khalwat** [comment]
So I look a look at the spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

> A whitelist for specific inline scripts using a cryptographic nonce (number used once). The server must generate a unique nonce value each time it transmits a policy. **It is critical to provide an unguessable nonce**, as bypassing a resource’s policy is otherwise trivial. See unsafe inline script for an example. Specifying nonce makes a modern browser ignore 'unsafe-inline' which could still be set for older browsers without nonce support.

The plugin you referenced does it thusly:

https://github.com/born05/craft-csp/blob/master/src/services/Headers.php#L125

It's not clear to me that this is unguessable, but if the random seed is isn't deterministic, I guess it'd be okay.

The rub here is that based on what I read, any nonces that are used in the script/style tags then also appear to need to be sent as part of the header as well.

It seems that to do this right, I'd need to send headers as well as applying the nonce to the script/style tags. Or were you envisioning handling that part yourself?

**Comment by khalwat** [comment]
@tomkiss okay I added support for `cspNonce` in https://github.com/nystudio107/craft-twigpack/commit/66a566cc8b80f434424c9d4161183bf6641d31a5

You can set your `semVer` to `dev-develop` and do a `composer update` to pull it down and give it a whirl.

I have not fully tested the implementation yet, so feedback would be great!

**Comment by khalwat** [comment]
Added in 1.2.2: https://github.com/nystudio107/craft-twigpack/releases/tag/1.2.2
