### ISSUE TITLE
webpack-dev-server/HMR not working in Nitro setup

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-twigpack#42]
I have a project setup, based on your Annotated Webpack config, that works perfectly in my Valet local environment setup. I cloned the project within a Nitro setup and everything works as expected—except for the webpack-dev-server/HMR. In my Twigpack config file, useDevServer is set to true as well as devMode in my general config. But Twigpack prints out the dist version of my JS and CSS (`/dist/js/app.###.js`) rather than the devServer verion (`http://localhost:8080/js/app.###.js`). Any idea what's going amiss with the Nitro setup?

**Comment by khalwat** [comment]
It's a VM, so probably you need setting more like I use for Homestead (check the docs).

But it depends on whether you run the webpack setup inside of the VM or outside of the VM, etc.

This isn't going to end up being a bug in Twigpack I don't think, but just a matter of getting the config settings right.

**Comment by tamlyn** [comment]
With Nitro 2.0 which is based on Docker, you can get this working with the following config, assuming you're running Webpack on the host.

In `twigpack.php`:

    'devServer' => [
        'manifestPath' => 'http://host.docker.internal:8080/',
        'publicPath' => 'http://localhost:8080/',
    ],

In `webpack.config.js`:

    devServer: {
      public: 'host.docker.internal'
    },

**Comment by khalwat** [comment]
Using webpack 5, you might need:

In `webpack.config.js`:
```js
  devServer: {
      firewall: false,
  }
```
