### ISSUE TITLE
includeCriticalCssTags() returns empty

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-twigpack#44]
`{{ craft.twigpack.includeCriticalCssTags() }}` always returns empty, even though my `twigpack.php` file is configured properly with the correct `'localFiles'` values. The respective critical css files also exist. 

I tried to directly pass in the path to the critical css file like this, but it still doesn't work: `includeCriticalCssTags("mypath/index_critical.min.css")`

`craft.twigpack.includeInlineCssTags(mypath/index_critical.min.css)`, however, does work, so I can't identify the source of the problem. 

Running Craft 3.4.25, Twigpack 1.2.3.

**Comment by khalwat** [comment]
I'm not sure what to tell you here... this works okay for me, I'm assuming it's some kind of setup/config issue on your end?
