### ISSUE TITLE
Hashes wrong (cache?) in production - ideas why?

### ISSUE THREAD

**Issue by janeschindler** [nystudio107/craft-twigpack#46]
This is a question about hashes or maybe about cache. I'm making a regular craft website with a few vue components.
When I do npm run build, everything works great locally. But when I push to the production site, which is on a shared host, the CSS and JS in dist/ is linked incorrectly. The links are there in the html, but the hashes are all wrong. I tried clearing the craft cache, but that did nothing. I have no idea where these original hashes are from anyway – I don't understand how the production site even knows about these files, which no longer exist. The dist/manifest.json gets pushed to production and has the right hashes, but these are not being used.
Does anyone know why this is? Am I missing something stupid?

To get around this for the moment: I turned off `filenameHashing` in vue.config.js. Then in _layout.twig, I took out `craft.twigpack.includeCssModule("app.css", true)` and `craft.twigpack.includeJsModule("app.js", true)` and instead wrote the links to the unhashed files manually. I assume this will cause caching problems later on, but I couldn't get anything else to work.

Thanks for any ideas.

**Comment by bryandugan** [comment]
Did you clear the cache in the Craft CP at Utilities > Clear Caches > Twigpack Manifest Cache?

I was just having the same issue and that fixed it for me on my production site.

Andrew also has a script that he uses to clear the cache on every deploy if that's helpful. [https://nystudio107.com/docs/twigpack/#caching](https://nystudio107.com/docs/twigpack/#caching)

Here is the way I also include Twigpack in my layouts if that's helpful.

Header
```
    {{ craft.twigpack.includeCssModule("app.css", true) }}

    {% if getenv('ENVIRONMENT') != 'dev' and getenv('ENVIRONMENT') != 'local' %}
        {{ craft.twigpack.includeCssModule("app.css") }}
    {% endif %}
```

Footer
```
{{ craft.twigpack.includeSafariNomoduleFix() }}
{{ craft.twigpack.includeJsModule("chunk-vendors.js", true) }}
{{ craft.twigpack.includeJsModule("app.js", true) }}
```

If it's none of that, then it may quite possibly be an issue with the shared hosting setup.

**Comment by janeschindler** [comment]
Thanks for looking at this. Yes, I cleared all caches many times. It's a good idea to find out more about hosting. I don't know that much about server setups. What do you suspect could be a problem? It would be good to have more info before I call up the host. 
-> Also, it would be good to know what kinds of disadvantages there might be to linking the CSS and JS without hashes, since that appears to be working right now. What is the reason for the hashes in the first place? Why does my app work fine without them?
Thanks.

**Comment by khalwat** [comment]
Hashes are there to ensure that when files change, the clients won't be using an outdated version of the scripts/CSS. 

See here for more: https://webpack.js.org/guides/caching/
