### ISSUE TITLE
Does update 1.2.4 removes the need for the styles.js workaround?

### ISSUE THREAD

**Issue by TomDeSmet** [nystudio107/craft-twigpack#48]
### Question
The styles.js workaround as described [here](https://github.com/nystudio107/annotated-webpack-4-config/issues/5), is it now obsolete?
Because I get an error `Undefined index: styles.js` when I leave this code in my layout.twig file: 
```<script nomodule>{{ craft.twigpack.includeFileFromManifest("styles.js") }}</script>```
But that code was needed to make Javascript work on IE11.

**Comment by khalwat** [comment]
You should leave that code in. All it should be doing is not logging that error.
