### ISSUE TITLE
support chunks-webpack-plugin

### ISSUE THREAD

**Issue by jaystacey** [nystudio107/craft-twigpack#49]
### Is your feature request related to a problem? Please describe.
support the inclusion of the related chunks created with webpack chunks: 'all'

### Describe the solution you would like
chunks-webpack-plugin manifest output example:

{
  "app": {
    "styles": [
      "/sample.com.au/dist/css/app.1dd06925.css"
    ],
    "scripts": [
      "/sample.com.au/dist/js/0.3405942a.js",
      "/sample.com.au/dist/js/1.ff95e12d.js",
      "/sample.com.au/dist/js/app.1dd06925.js"
    ]
  },
  "product": {
    "styles": [],
    "scripts": [
      "/sample.com.au/dist/js/0.3405942a.js",
      "/sample.com.au/dist/js/product.1f565b46.js"
    ]
  }
}

### Describe alternatives you have considered

include a function along side: {{ craft.twigpack.includeJsModule("app.js") }}  
could be {{ craft.twigpack.includeJsModules(["app","product"]) }}  with array of modlue names, then strip duplicated paths and output in order script tags.

true multi page shared chunks.

Also include the style option, in addition to {{ craft.twigpack.includeCssModule("app.css", false) }} include a {{ craft.twigpack.includeCssModules(["app","products") }} same functionality as JsModules for styles.

### Additional context
adding new function for backwards compat.

**Comment by khalwat** [comment]
@jaystacey I personally wouldn't be likely to use this, because I typically am doing dynamic imports for things like this... but I'd be happy to accept a PR!
