### ISSUE TITLE
Let me define a fallback CSS file for criticalcss

### ISSUE THREAD

**Issue by Mosnar** [nystudio107/craft-twigpack#52]
### Is your feature request related to a problem? Please describe.
Generating critical css for every element template is a bit overkill and they're frequently the same (especially if you're making heavy use of layouts). There should be a way to define fallback critical css files when twigpack isn't able to locate one dynamically.

### Describe the solution you would like
A simple config setting for "criticalDefault" that would accept a file would suffice. Alternatively, the `includeCriticalCssTags()` function could accept a fallback, akin to Twig's `{% include() %}` tag. 

### Describe alternatives you have considered
The logic could be handled in Twig; however, it would be a lot of logic to have in a template. Alternatively, an event could be thrown to modify the criticalcss file to load; however, this feels a little overkill to me.

**Comment by khalwat** [comment]
What I do for this is something like:

```twig
    {{ craft.twigpack.includeFileFromManifest('styles.css') }}
```
 (I do the above for AMP pages now, for example)

But if you want to change the critical CSS that's loaded, you can pass in the name of the template to use to `includeCriticalCssTags()`:

```php
    /**
     * Returns the Critical CSS file for $template wrapped in <style></style>
     * tags
     *
     * @param null|string $name
     * @param array $attributes additional HTML key/value pair attributes to add to the resulting tag
     *
     * @return Markup
     * @throws \Twig\Error\LoaderError
     */
    public function includeCriticalCssTags($name = null, array $attributes = []): Markup
    {
        return Template::raw(
            Twigpack::$plugin->manifest->getCriticalCssTags($name, null, $attributes) ?? ''
        );
    }
```

Which will cause it to look for the appropriate critical CSS file for whatever template you specify. There is also:

```php
    /**
     * Returns the CSS file in $path wrapped in <style></style> tags
     *
     * @param string $path
     * @param array $attributes additional HTML key/value pair attributes to add to the resulting tag
     *
     * @return Markup
     */
    public function includeInlineCssTags(string $path, array $attributes = []): Markup
    {
        return Template::raw(
            Twigpack::$plugin->manifest->getCssInlineTags($path, $attributes) ?? ''
        );
    }
```
