### ISSUE TITLE
"modern" script not loaded when async is missing

### ISSUE THREAD

**Issue by qbasic16** [nystudio107/craft-twigpack#54]
### Describe the bug
I use Twigpack in all Craft my projects in combination with Webpack, it's a great plugin!

Recently I found out that my ES6 scripts are not getting loaded by the browser, so I went digging.
I have found out that since the change in Twigpack was made, where you could define to include the script as async (in `includeJsModule`), it will only load the legacy script.

### To reproduce
Steps to reproduce the behaviour:
1. In `twigpack.php` define legacy and modern manifest files (default) and set `useDevServer` to `false`.
2. In a twig template include the JS module like so:
```twig
{{ craft.twigpack.includeJsModule("site.js") }}
```
3. Load the website
4. The browser will only load the legacy module script.
```html
<script src="http://xyz.local/site-es5.js"></script>
```

### Expected behaviour
The browser should load both modules: Modern and legacy

```html
<script type="module" src="http://xyz.local/site-es2015.js"></script>
<script src="http://xyz.local/site-es5.js" nomodule></script>
```

### Fix
Set async to true:
```twig
{{ craft.twigpack.includeJsModule("site.js", true) }}
```

### Versions
- Plugin version: 1.2.7
- Craft version: 3.5.17.1

### Additional notes

I think this behavior should be fixed in code. In my opinion the async parameter is **misleading** for `craft.twigpack.includeJsModule(...)`.

In the docs unter ["Including JavaScript"](https://nystudio107.com/docs/twigpack/#including-javascript) you state:

> You can also include a second optional parameter, to determine whether the JavaScript module should be loaded asynchronously or not (it defaults to false).

This does not mention, that in the case of `false`, no modern script will be loaded.

On MDN they state:

> There is no need to use the defer attribute (see <script> attributes) when loading a module script; modules are deferred automatically.

Source: [Modules - Other_differences_between_modules_and_standard_scripts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Other_differences_between_modules_and_standard_scripts)

**Comment by qbasic16** [comment]
To be honest, I'm not quite sure if this falls under the category of "bug".

Your docs have examples of what is output when, but I think the whole naming of the "async" parameter to define whether the `modern` script will be included or not, is rather misleading, in my opinion.

**Comment by khalwat** [comment]
Yeah I don't think it's a bug, I think it's just poorly documented. It's called "async" precisely because JS modules will always be loaded as deferred (async loaded, but not run until the document is ready). I'll clean it up in the docs.
