### ISSUE TITLE
Issues with twigpack cache on Heroku

### ISSUE THREAD

**Issue by timkelty** [nystudio107/craft-twigpack#56]
I'm pretty sure this is nothing Twigpack is doing wrong, but logging here in case someone else runs into the same thing.

To clear caches on deploy, you would run a script or command on release, eg this in your `Procfile`:

```
release: ./craft clear-caches/data
```

That runs, and runs successfully, but I end up with broken assets until I manually run it again.

I suspect what is happening is the command is in fact clearing the cache, but then a subsequent incoming request re-caches (the old) assets, before the deploy is fully complete.

So, I'm trying to see if there is some "post-successful deploy" thing for Heroku.

FWIW, I'm also trying `dev-develop`, as the FileDependency stuff might help here when things get out of sync.

**Comment by khalwat** [comment]
thx @timkelty -- but I didn't add any FileDependency stuff?

**Comment by timkelty** [comment]
No _you're_ drunk https://github.com/nystudio107/craft-twigpack/blob/develop/CHANGELOG.md#added

**Comment by khalwat** [comment]
Wasn't sure, so searched the codebase on `FileDependency` -- no results but:

<img width="251" alt="Screen Shot 2021-02-25 at 10 33 50 PM" src="https://user-images.githubusercontent.com/7570798/109251511-9ce76e80-77b9-11eb-80f2-9de7500ac6f1.png">

...oops. Gotta pull

**Comment by khalwat** [comment]
Released in https://github.com/nystudio107/craft-twigpack/releases/tag/1.2.10
