### ISSUE TITLE
Hard error on missing critical templates

### ISSUE THREAD

**Issue by michaelroper** [nystudio107/craft-twigpack#6]
Hey Andrew! Is it possible to make twigpack treat missing critical CSS templates as soft errors (similar to #2) instead of a hard 404 twig error when using the `{{ craft.twigpack.includeCriticalCssTags() }}` tag?

**Comment by khalwat** [comment]
Hmmmm. Yeah it should be doing that, I agree.

**Comment by khalwat** [comment]
Implemented in 1.1.3: https://github.com/nystudio107/craft-twigpack/releases/tag/1.1.3

**Comment by michaelroper** [comment]
Smashing, thanks mate!
