### ISSUE TITLE
Request to mix-manifest.json is malformed

### ISSUE THREAD

**Issue by paweltatarczuk** [nystudio107/craft-twigpack#62]
### Describe the bug

We have experienced an extremely weird case with craft-twigpack not being able to connect with the webpack-dev-server properly.

During the craft-twigpack initialization there is a request to webpack-dev-server like so:

```
GET http://localhost:8080/mix-manifest.json
User-Agent: User-Agent:Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13

Accept: */*
```

Clearly this is not a valid HTTP request.

### To reproduce
Steps to reproduce the behaviour:
1. Set up a craft-twigpack with webpack-dev-server (HMR enabled)
2. Try visiting a Craft's page
3. Webpack responds with 400 Bad request

This should be easily seen with a `tcpflow`:

```
$ sudo tcpflow -c -i any host localhost and port 8080
```

### Expected behaviour

Request to the webpack should be a well-formed HTTP request:

```
GET http://localhost:8080/mix-manifest.json
User-Agent: User-Agent:Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13
Accept: */*
```

### Investigation

We couldn't get craft-twigpack to work with our docker-compose setup. We've went through a debug session and found out a root cause of the issue:

https://github.com/nystudio107/craft-twigpack/blob/v1/src/helpers/Manifest.php#L613

We were seeing a 400 Bad Request response and not expected 200 OK even though webpack-dev-server was responding.

Changing the mix-manifest request from:

```
$client->request('GET', $path, [
    RequestOptions::HEADERS => [
        'User-Agent' => "User-Agent:Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13\r\n",
        'Accept' => '*/*',
    ],
]);
```

To:

```
$client->request('GET', $path, [
    RequestOptions::HEADERS => [
        'User-Agent' => "User-Agent:Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13",
        'Accept' => '*/*',
    ],
]);
```

Resulted with a 200 OK response.

We saw a following request while debugging this issue:

```
$ sudo tcpflow -c -i any host 172.18.0.2

172.018.000.003.48494-172.018.000.002.08080: GET /mix-manifest.json HTTP/1.1
Host: node:8080
User-Agent: User-Agent:Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13

Accept: */*


172.018.000.002.08080-172.018.000.003.48494: HTTP/1.1 400 Bad Request
Connection: close
```

Seems like the extra `\r\n` is causing Guzzle to add an empty line before `Accept` header turning the header into request's body.

### Versions
- Plugin version: 1.2.12
- Craft version: 3.5.19.1

**Comment by khalwat** [comment]
Fantastic detective work @paweltatarczuk and thank you for the PR as well!

**Comment by khalwat** [comment]
Merged & fixed in https://github.com/nystudio107/craft-twigpack/releases/tag/1.2.13
