### ISSUE TITLE
Aliases like @webroot not working

### ISSUE THREAD

**Issue by kevinmu17** [nystudio107/craft-twigpack#65]
### Describe the bug
In the [docs](https://nystudio107.com/docs/twigpack/#configuring-twigpack) there is a use case of the alias @webroot
```
'server' => [
    'manifestPath' => '@webroot/',
    'publicPath' => '/',
],
```

### To reproduce
Steps to reproduce the behaviour:
1. Set the manifestPath to `'@webroot'`
2. Make sure you've setup the alias in the config/general.php
3. Run a production build with NPM and make sure you set your .ENV (ENVIRONMENT=production)
4. Use {{ craft.twigpack.getModuleUri("main.js") }} in you twig template
4. Error message: Cat:nystudio107\twigpack\helpers\Manifest::reportError Message: Manifest file not found at: @webroot

### Expected behaviour
@webroot alias should be converted so the path is correct ( Craft::getAlias('@webroot') )

### Versions
- Plugin version: 1.2.13
- Craft version: 3.6.12

**Comment by khalwat** [comment]
I'm using a config exactly like that in production here without issues:

https://github.com/nystudio107/devmode/blob/master/cms/config/twigpack.php#L40

Are you sure there isn't something wrong with your alias? The code _does_ resolve aliases:

https://github.com/nystudio107/craft-twigpack/blob/v1/src/helpers/Manifest.php#L521

**Comment by kevinmu17** [comment]
> Are you sure there isn't something wrong with your alias? The code _does_ resolve aliases:

Yes 100% sure. 

The weird thing is, when using {{ craft.twigpack.getModuleUri("main.css") }} it is returning the correct url and filenames.
but when using {{ craft.twigpack.includeCssModule("main.css") }} it returns nothing. Debug toolbar is throwing me the error.

**Comment by khalwat** [comment]
That being the case... my website should be broken too :)

https://github.com/nystudio107/devmode/blob/master/cms/templates/_boilerplate/_partials/critical-css.twig#L13

Here's what that PHP function does: 
```php
    /**
     * @param array $config
     * @param string $moduleName
     * @param bool $async
     * @param array $attributes additional HTML key/value pair attributes to add to the resulting tag
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public static function getCssModuleTags(array $config, string $moduleName, bool $async, array $attributes = []): string
    {
        $legacyModule = self::getModule($config, $moduleName, 'legacy', true);
        if ($legacyModule === null) {
            return '';
        }
        $lines = [];
        if ($async) {
            $lines[] = Html::cssFile($legacyModule, array_merge([
                'rel' => 'stylesheet',
                'media' => 'print',
                'onload' => "this.media='all'",
            ], $attributes));
            $lines[] = Html::cssFile($legacyModule, array_merge([
                'rel' => 'stylesheet',
                'noscript' => true,
            ], $attributes));
        } else {
            $lines[] = Html::cssFile($legacyModule, array_merge([
                'rel' => 'stylesheet',
            ], $attributes));
        }

        return implode("\r\n", $lines);
    }
```

Are you perhaps not producing legacy builds? If so, ensure you set both the legacy and the modern manifest settings to `manifest.json`

**Comment by kevinmu17** [comment]
> Are you perhaps not producing legacy builds? If so, ensure you set both the legacy and the modern manifest settings to `manifest.json`

You sir, saved my day. I totally missed that part in the docs sorry for that! But out of curiosity, when using `{{ craft.twigpack.includeJsModule("main.js", true) }}` It is activating legacy mode right?

**Comment by khalwat** [comment]
CSS defaults to the legacy bundle build, JS defaults to the modern bundle build.

There's more on it here:

https://nystudio107.com/blog/an-annotated-webpack-4-config-for-frontend-web-development#common-conventions-for-webpack-configs

Glad you got it sorted!
