### ISSUE TITLE
ViteJS Support

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-twigpack#66]
### Describe the solution you would like
Support for ViteJS: https://vitejs.dev (looks like this is just handling their custom manifest file)

### Describe alternatives you have considered
Currently have this working via a rollup mainfest plugin (https://github.com/shuizhongyueming/rollup-plugin-output-manifest) from within the ViteJS config but seems like a nice feature for TwigPack would be to allow non flat file mainfests.

**Comment by khalwat** [comment]
Yeah it's on my list to do something like this...

**Comment by baileydoestech** [comment]
As reference this is the working `vite.config.ts` we have to generate a compatible manifest file for Twigpack to use

```
import { defineConfig } from 'vite';
import outputManifest from 'rollup-plugin-output-manifest';
import { join } from 'path';

export default defineConfig({
    base: '/build/',
    build: {
        emptyOutDir: true,
        outDir: 'web/build',
        assetsDir: '',
        rollupOptions: {
            input: {
                common: '/src/index.ts'
            },
            plugins: [
                outputManifest({
                    nameSuffix: '',
                    outputPath: join(__dirname, 'web/build'),
                    filter: a => !!a
                })
            ]
        }
    }
});
```

If you could support the custom manifest that they use then this would be simplified to the following and remove depedancy on rollup plugin (which looks to no longer be supported):

```
import { defineConfig } from 'vite';

export default defineConfig({
    build: {
        manifest: true,
        emptyOutDir: true,
        outDir: 'web/build',
        assetsDir: '',
        rollupOptions: {
            input: {
                common: '/src/index.ts',
            }
        }
    }
});
```

**Comment by khalwat** [comment]
@lukebailey can you post example manifest file output too? First what Vite outputs by default, and second what your transformed version looks like?

**Comment by baileydoestech** [comment]
Based on a single entry point (`src/index.ts` named as `main`).

ViteJS Manifest file (not compatible)

```
{
  "src/index.ts": {
    "file": "main.8b71d7e0.js",
    "src": "src/index.ts",
    "isEntry": true,
    "imports": [
      "_vendor.22340ed1.js"
    ],
    "css": [
      "main.e2213e69.css"
    ],
    "assets": [
      "32DFE6_0_01755a51484a24f49af6b.3f65127a.woff",
      "32DFE6_4_02b7481f5420ec6f47a23.abaf87d5.woff",
      "32DFE6_3_0ce9c5940b9ab821276ea.94257182.woff",
      "32DFE6_5_07a6963b32d4e5460ef45.072ccb67.woff",
      "32DFE6_1_0f42d493cd5a6d1f82c45.c13a4d7c.woff",
      "32DFE6_2_00a211ce1ff1b11e0de45.af53f4a8.woff",
      "32DFE6_6_05358e428b3e0ac99b46e.0b483b60.woff",
      "OpenSans-Extraboldadb8793a077b993882fc.fb042d52.woff",
      "OpenSans-Bold9c47331ca0ce2ef16905.2f30fd9a.woff",
      "OpenSans-Semibolda1cc523638ef17458032.ae533555.woff",
      "OpenSansd0c6e2dcac826fe1c798.8095261c.woff",
      "OpenSans-Light7d886dbd77aecac20cc5.a1797fe5.woff"
    ]
  },
  "_vendor.22340ed1.js": {
    "file": "vendor.22340ed1.js"
  }
}
```

Transformed manifest file (compatible):

```
{
  "main": "main.8b71d7e0.js",
  "main.css": "main.e2213e69.css",
  "vendor": "vendor.22340ed1.js"
}
```

**Comment by khalwat** [comment]
How is that plugin resolving the `vendor` bundle here? The source manifest already looks like it's transformed/versioned?

```json
  "_vendor.22340ed1.js": {
    "file": "vendor.22340ed1.js"
  }
```

**Comment by khalwat** [comment]
Also @lukebailey if you're using Twig, how is Vite finding the JS files you want it to build?

**Comment by khalwat** [comment]
@lukebailey Would you have any time to chat for a little bit about how you were using Vite? Hit me up on the Craft Discord?

I’ve been exploring it a bit lately and it appears that its use of index.html as entry point code is problematic with using it with Craft

**Comment by khalwat** [comment]
Having investigated this a good bit, I think the solution is a separate plugin. It just makes it easier to do things the "Vite" way:

https://github.com/nystudio107/craft-vite

(still in development at the time of this writing)

**Comment by khalwat** [comment]
@lukebailey ICYMI Vite plugin released: https://github.com/nystudio107/craft-vite

Docs are up… article will be coming soon that's more explanatory, less reference: https://nystudio107.com/docs/vite
