### ISSUE TITLE
Rendering templates with multiple getModuleUri calls is extremely slow after release v1.2.12

### ISSUE THREAD

**Issue by aurexs** [nystudio107/craft-twigpack#67]
### Describe the bug

Multiple calls to `craft.twigpack.getModuleUri()` in a template cause the contents of the manifest file to be read on each call. Each content reading causes a GuzzleHttp request with a delay that builds up as the template is rendered.

The commit b4f2c34b8c938d6b899261c5b562ca5c5a71119f "Add a 100ms delay when requesting the manifest file..." effectively adds a delay in reading the manifest content but if hot mode is enabled and devserver is not running, it causes a cascading delay when rendering the template (more than 5 seconds in a typically 200ms template).

### To reproduce

1. In config `twigpack.php`, set `'useDevServer' => true` and enable devMode in craft config.
2. Ensure webpack-dev-server is not running.
3. In a twig template, call `craft.twigpack.getModuleUri` multiple times (i'm loading optimized versioned svg and images from the manifest file in this way)

### Expected behaviour

The rendering of the page should not be slow.

The content of the manifest file should be read only once and its content should be cached for at least the current request, so a delay of 100ms would be acceptable.

### Versions

- Plugin version: >= 1.2.12
- Craft version: 3

**Comment by khalwat** [comment]
Thx for the report @aurexs -- should be fixed in: https://github.com/nystudio107/craft-twigpack/releases/tag/1.2.14
