### ISSUE TITLE
Multisite setup

### ISSUE THREAD

**Issue by dGilli** [nystudio107/craft-twigpack#7]
Since the plugin grabs the `siteUrl` and the language segments get attached to the path. Twigpack does not find the manifest files while on anything other than the primary site.

```
'siteUrl' => [
    'en' => getenv('CRAFTENV_SITE_URL') . 'en/',
    'de' => getenv('CRAFTENV_SITE_URL') . 'de/' ,
    'fr' => getenv('CRAFTENV_SITE_URL') . 'fr/',
],
```

**Comment by jermashley** [comment]
Howdy.  Does anyone have any suggestions to get twigpack working with multiple sites?

**Comment by FreakyFlu** [comment]
what was the solution here? Facing the same issue

**Comment by fthues** [comment]
Same here. Did you find a solution, @dGilli ?

**Comment by dGilli** [comment]
I got it to work just as Andrew describes in #24.

**Comment by puck3000** [comment]
Care to share the relevant parts of your general.php and twigpack settings? I seem to be missing something…

**Comment by kristiansp** [comment]
@puck3000 I've just been grappling with this too, and finally found a solution that works for me, at least. Basically setting the server config to absolute paths with environmental variables:

NB! This assumes that your `BASE_URL` ends with a `/`, as I just discovered when deploying this to server.
```
        // Public server config
        'server' => [
            'manifestPath' => getenv('BASE_URL') . 'dist/',
            'publicPath' => getenv('BASE_URL'),
        ],
```

**Comment by umkasanki** [comment]
guys, avoid using urls in 'manifestPath', this may not work on some servers.

> andrew.welchYesterday at 7:10 PM
> 'manifestPath' => getenv('BASE_URL') . '/build/',
> should be a file system path like maybe:
> 'manifestPath' => '@webroot/build/',
> or something (depending on your setup)

working multilangual config:
```
'server' => [
	'manifestPath' => '@root/web/build/', // eg '/opt/approot/current/web/build/',
	'publicPath' => getenv('BASE_URL') . '/', // eg 'https://site.com/'
],
```
