### ISSUE TITLE
getModuleUri giving the correct URL to CSS but includeCssModule doesn't include the CSS on the page

### ISSUE THREAD

**Issue by lukew-cogapp** [nystudio107/craft-twigpack#79]
Hello,

We just got HMR working with Twigpack - great! However, the built CSS link isn't being added to the page.

When running Webpack Dev Server the following tag results in the CSS link being added to the page:
`{{ craft.twigpack.includeCssModule("main.css") }}`

However, when building the files, this same tag results in no CSS link being rendered.

I was originally thinking there was some configuration issue in `twigpack.php` - but I've just tested the following tag and it outputs the location to the CSS:
`{{ craft.twigpack.getModuleUri("main.css") }}`

Therefore this demonstrates that Twigpack can successfully find the `manifest.json` file and get the path to `main.css`.

A temporary work around is the following, but not ideal:
```twig
{% set cssURL = craft.twigpack.getModuleUri("main.css") %}
{% css cssURL %}
```

The relevant bit of `twigpack.php`:
```PHP
'server' => [
            'manifestPath' => 'https://siteurl.site/assets/',
            'publicPath' => 'https://siteurl.site/',
        ],
        // webpack-dev-server config
        'devServer' => [
            'manifestPath' => 'http://localhost:8081/assets/',
            'publicPath' => 'http://localhost:8081/',
        ],
```

When running the Webpack build, this results in the CSS being created in `web/assets/css` and `manifest.json` being created in `web/assets`. Here is the contents of the `manifest.json`:
```JSON
{
  "main.css": "/assets/css/main.css"
}
```

Any help appreciated!

**Comment by khalwat** [comment]
Twigpack by default looks for CSS as part of the legacy build, so that's probably what is going on. Are you not generating dual legacy/modern builds?

So either use dual legacy/modern builds, or alter the `config.php` to point the `manifest. legacy ` at your singular `manifest.json`:

https://github.com/nystudio107/craft-twigpack/blob/develop/src/config.php#L39

**Comment by lukew-cogapp** [comment]
Thanks, I missed this in the docs :)
