### ISSUE TITLE
Twigpack is stuck on where it thinks mix-manifest is located

### ISSUE THREAD

**Issue by proimage** [nystudio107/craft-twigpack#80]
### Question
I've got a site using Laravel Mix, and am coming from a `misterbk/mix` plugin setup. Due to the site spanning various load-balanced servers, I need to have root-relative URLs, instead of absolute domain URLs. I've got it working just fine locally (using ddev under Windows), but I can't for the life of me get it to work on the remote server.

Relevant paths:
Manifest: `@webroot/mix-manifest.json`
CSS: `@webroot/assets/css/all.css`
JS: `@webroot/assets/js/app.css`

mix-manifest.json has:
```json
{
    "/assets/js/app.js": "/assets/js/app.js?id=b1341a8e6d5d440d33f67925d0e0d5d1",
    "/assets/css/all.css": "/assets/css/all.css?id=a0089034478a1be737d8cf5ad8f6f704",
}
```

My layout template is referring to the above files like so:
```twig
<link rel="stylesheet" href="{{ craft.twigpack.getModuleUri('/assets/css/all.css') }}" title="All styles">
...
<script src="{{ craft.twigpack.getModuleUri('/assets/js/app.js') }}" defer></script>
```

Finally, my `config/twigpack.php` in its entirety:

```php
<?php

	return [
		// Global settings
		'*' => [
			// If `devMode` is on, use webpack-dev-server to all for HMR (hot module reloading)
			'useDevServer' => false,
			// Enforce Absolute URLs on includes
			'useAbsoluteUrl' => false,
			// The JavaScript entry from the manifest.json to inject on Twig error pages
			// This can be a string or an array of strings
			'errorEntry' => '',
			// String to be appended to the cache key
			'cacheKeySuffix' => '',
			// Manifest file names
			'manifest' => [
				'legacy' => 'mix-manifest.json',
				'modern' => 'mix-manifest.json',
			],
			// Public server config
			'server' => [
				'manifestPath' => '@webroot/',
				'publicPath' => '/',
			],
			// webpack-dev-server config
			'devServer' => [
				'manifestPath' => '@webroot/',
				'publicPath' => '/',
			],
			// Bundle to use with the webpack-dev-server
			'devServerBuildType' => 'modern',
			// Whether to include a Content Security Policy "nonce" for inline
			// CSS or JavaScript. Valid values are 'header' or 'tag' for how the CSP
			// should be included. c.f.:
			// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script
			'cspNonce' => '',
			// Local files config
			'localFiles' => [
				'basePath' => '@webroot/',
				'criticalPrefix' => 'dist/criticalcss/',
				'criticalSuffix' => '_critical.min.css',
			],
		],
		// Development environment
		'dev' => [
			// If `devMode` is on, use webpack-dev-server to all for HMR (hot module reloading)
			'useDevServer' => true,
		],
		// Staging (pre-production) environment
		'staging' => [
		],
		// Live (production) environment
		'production' => [
		],
	];
```

Now, when I load the site in that state, there's no output from the `{{ craft.twigpack.getModuleUri() }}` tags, and the `web.log` shows:
```log
2022-07-28 14:22:10 [-][123042][-][error][nystudio107\twigpack\helpers\Manifest::reportError] Manifest file not found at: @webroot/assets/
```

Now, uhh, it's probably worth noting at this point that I _used to have_ things set up in the recent past to use a `mix-manifest.json` located at `@webroot/assets/mix-manifest.json` (and in all honesty, I can go back to using it there if it makes any difference). However, as you can see, I have excised all references that I can find to that being the path, and yet somehow, Twigpack still thinks that mix-manifest is located under `@webroot/assets/`. 🤨 

And yes, I have cleared the Twigpack Manifest cache (as well as all the other ones that don't have to do with image transforms), to no avail.

Any pointers? 🆘 What am I missing?

**Comment by khalwat** [comment]
Check your error logs -- there most likely is an error from Twigpack stating that it can't find the manifest file.

Is the manifest.json really at `@webroot/manifest.json`?

**Comment by proimage** [comment]
There _are_ no error logs per se; just the `web.log` as stated in the OP.

And no, `manifest.json` isn't anywhere... it's `mix-manifest.json`, and it is accessible from `example.com/mix-manifest.json`.

**Comment by khalwat** [comment]
I see several places in the code where errors should be logged:

If it can't find the module entry you're asking for: https://github.com/nystudio107/craft-plugin-manifest/blob/af2cd16f3a199314b9afba3b31c49afc8bbb50b5/src/services/ManifestService.php#L311

If it can't find the manifest file: https://github.com/nystudio107/craft-plugin-manifest/blob/af2cd16f3a199314b9afba3b31c49afc8bbb50b5/src/services/ManifestService.php#L348

If nothing is output, an error should be logged, I'd think.

**Comment by proimage** [comment]
Like I said above, there's no error logs (i.e. `error.log` files), but there IS the error in `web.log`. Did you miss that in the first post? You need to scroll it to the right to see the error message... ;)

**Comment by khalwat** [comment]
> 2022-07-28 14:22:10 [-][123042][-][error][nystudio107\twigpack\helpers\Manifest::reportError] Manifest file not found at: @webroot/assets/

It's looking for your manifest file in `@webroot/assets/mix-manifest.json` -- why, I'm not sure. Perhaps you don't clear caches on deploy, and it's cached? 

Put it there, and it should work as expected.

**Comment by proimage** [comment]
Right, but here's the second layer of this conundrum:

When `mix-manifest.json` is located under the `@webroot/assets/` directory, then the paths to the compiled assets inside `mix-manifest.json` are not root-relative, but `/assets/`-relative:

```json
{
    "/js/app.js": "/js/app.js?id=4078d3bacd5bec58043bdcf2919fe0b2",
    "/css/all.css": "/css/all.css?id=1358f72d4f09b6629328c29d336d4540",
}
````

Twigpack handles that fine when the `useAbsoluteUrl` option is `true`, but when that setting is `false`, it just outputs the paths found in the manifest file. This means the site HTML has this:

```html
<!-- Wrong URL -->
<link rel="stylesheet" href="/css/all.css?id=1358f72d4f09b6629328c29d336d4540">
```

...instead of this:

```html
<!-- Right URL -->
<link rel="stylesheet" href="/assets/css/all.css?id=1358f72d4f09b6629328c29d336d4540">
```

My overall goal here is to get output like that last code block... root-relative URLs to the assets, without the domain being specified. This bug report was just one hiccup on my route to that goal.

**Comment by khalwat** [comment]
Please clear your caches, if you had it working before, probably it's something cache related.

**Comment by proimage** [comment]
Ok, so a co-worker of mine tackled this last night, and he has access to more cache-clearing powers than I do (I only have Craft's stuff; he can access Redis, Cloudflare, etc). Somehow, he solved this ("Somehow, Palpatine returned." 🤮). Wish I could say exactly what the problem was, but I guess we can just close this out. Sorry, man!
