### ISSUE TITLE
4.0.0 release

### ISSUE THREAD

**Issue by ryssbowh** [nystudio107/craft-twigpack#82]
Hi,

Wondering if a stable release for Craft 4 is planned to be released soon ?
Thanks

**Comment by Siyabulela** [comment]
I had this problem after upgrading Craftcms to 4. It didn't wanna install. I added `"minimum-stability": "dev"` in composer.json

**Comment by khalwat** [comment]
Ah yes, I will cut a release shortly.

**Comment by stillhartkonzept** [comment]
any updates on this @khalwat ? Thanks!

**Comment by khalwat** [comment]
Version 4.0.0 released -> https://github.com/nystudio107/craft-twigpack/releases/tag/4.0.0
