### ISSUE TITLE
Craft 5 & Craft 4 out of beta

### ISSUE THREAD

**Issue by johannesSolvr** [nystudio107/craft-twigpack#87]
Hi, Will there be a Craft 5 version of this plugin. Wondering since Craf 4 version is still in beta.

**Comment by khalwat** [comment]
Yes there will. It's likely to be the next one I port, should be done this week.

**Comment by khalwat** [comment]
Released for Craft 5: https://github.com/nystudio107/craft-twigpack/releases/tag/5.0.0-beta.1
