### ISSUE TITLE
includeCriticalCssTags not working when setting own path

### ISSUE THREAD

**Issue by OneX** [nystudio107/craft-twigpack#9]
Tried to use {{ craft.twigpack.includeCriticalCssTags("/path/to/foo.css") }}.

I did not get any error and inline CSS tags were not included.

This worked as replacement {{ craft.twigpack.includeInlineCssTags("@webroot/foo.css") }}

**Comment by khalwat** [comment]
^ there probably was an error logged in the `web.log` -- in any event, I think the use of an alias is likely preferred.
